services:
  keycloak:
    image: "quay.io/keycloak/keycloak:25.0"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - "./keycloak_realm_config:/opt/keycloak/data/import"
    command: start-dev --import-realm
    ports:
      - "8080:8080"
