[package]
name = "printer-ldap"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "~1.0.83"
giz-ldap-lib = { path="../ldap-lib" }
keycloak = "~24.0.301"
tokio = { version = "~1.38.0", features = ["io-util"] }
